version: "3.8"

services:
  server:
    image:  'nginx:stable-alpine'
    ports:
     - '80:80'
    volumes :
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
     - ./src:/var/www/html:delegated
     - ./src/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  mysql:
   platform: linux/x86_64 
   image: mysql:8
   env_file:
    - ./env/mysql.env
