version: "3.8"

services:
  nginx:
    container_name: bf_nginx
    image: nginx:1.19
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: bf_php
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - chromedriver
  python:
    container_name: bf_captcha_ai
    image: python:3-buster
    volumes:
      - ./captcha-ai:/var/www/html
  db:
    container_name: bf_db
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      - ./etc/mysql/entrypoint.sh:/entrypoint.sh
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bf
      MYSQL_DATABASE_CHARSET: utf8
      MYSQL_DATABASE_COLLATE: utf8_unicode_ci
      MYSQL_USER: bf
      MYSQL_PASSWORD: bf
  chromedriver:
    container_name: bf_chromedriver
    image: selenium/standalone-chrome:4.1.2-20220217
    shm_size: '2gb'
    ports:
      - '4444:4444'
      - '5900:5900'

