version: "3.8"

services:
  nginx:
    container_name: bf_nginx
    image: nginx:1.19-alpine
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    container_name: bf_php
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  db:
    container_name: bf_db
    platform: linux/x86_64
    image: mysql:8
    expose:
      - 3306
    volumes:
      - ./etc/mysql/entrypoint.sh:/entrypoint.sh
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bf
      MYSQL_DATABASE_CHARSET: utf8
      MYSQL_DATABASE_COLLATE: utf8_unicode_ci
      MYSQL_USER: bf
      MYSQL_PASSWORD: bf